### ISSUE TITLE
confusing filenames; at least add version numbers

### ISSUE THREAD

**Issue by cordphelps** [evothings/evothings-examples#141]
comparing your instantiation to evothings-gallery/bluno-demo/app/libs/easyble.js (please)

**Comment by divineprog** [comment]
Thanks for observing this. You are absolutely right that it is confusing which version of the library you are using. We will look into how to address this and how to specify version numbers.

**Comment by divineprog** [comment]
Hi we have added a file to the evothings folder in the libraries with the release version number in its name. What do you think of this? A start at least. It should make sense to have it in the evothings folder since many of the libraries depend on evothings.js.

See this commit: https://github.com/divineprog/evothings-examples/commit/2da88fc7af17c67beb54b456a8234b646b58aeb6

**Comment by cordphelps** [comment]
that looks like a good start but, obviously, the confusion comes when
evothings.js or easyble.js are referenced in an index.html; it should be
clear there what versions are being used.

(like the jquery model ??)

thank you.

**Comment by divineprog** [comment]
We have decided to close this issue and use the solution with the version file in the library directory for the coming releases.
